# xingchen-utils
SERVICE_NAME_KEY = "SERVICE_NAME"
OTLP_ENABLE_KEY = "OTLP_ENABLE"
OTLP_DC_KEY = "OTLP_DC"
OTLP_SERVICE_NAME_KEY = "OTLP_SERVICE_NAME"

SERVICE_SUB_KEY = "SERVICE_SUB"
SERVICE_LOCATION_KEY = "SERVICE_LOCATION"
SERVICE_PORT_KEY = "SERVICE_PORT_KEY"

KAFKA_TOPIC_KEY = "KAFKA_TOPIC"
KAFKA_THREAD_NUM_KEY = "KAFKA_THREAD_NUM"
